### PR TITLE
A small correction and some code clean(black isort and ruff)

### PR DESCRIPTION
**Pull request by littlewhitecloud**
@akascape The repo is very great tbh. But there is still a little bug.
image
Idk why, but fixed.

### CODE REVIEW

**Comment by littlewhitecloud** [comment]
Also, I find the font "AIGDT" looks much better than default.
```default```
image
```AIGDT```
image

**Comment by Akascape** [comment]
@littlewhitecloud Thanks for the improvements, I will review it later

**Comment by littlewhitecloud** [comment]
LOL, is there anything wrong? @Akascape

**Comment by Akascape** [comment]
@littlewhitecloud Nah, this is the second time someone is making a code clean pull request.

**Comment by littlewhitecloud** [comment]
LOL, Actually it is a little bug fix pr. (I used black and isort and ruff because I want to check if there is something wrong in the code)

**Comment by littlewhitecloud** [comment]
So

**Comment by Akascape** [comment]
So

**Comment by Akascape** [comment]
@littlewhitecloud Don't worry, I will merge this pull request later.

**Review by Akascape — APPROVED** [review]

**Comment by Akascape** [comment]
@littlewhitecloud Ok, I have merged this pull request.
> Also, I find the font "AIGDT" looks much better than default.

I know, but the default one is in-built font of ImageFont: `ImageFont.load_default()`, doesn't matter but loading default parameters are always better.

**Pull request merged**
